package ganserv

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strconv"
	"strings"
)

type Route struct {
	Target string `json:"target"`
	Via    string `json:"via,omitempty"`
}

type IPv6Mode struct {
	ZT       bool `json:"zt"`
	RFC4193  bool `json:"rfc4193"`
	SixPlane bool `json:"6plane"`
}

type AdvancedNetworkSettings struct {
	// Addressing
	CIDR    string `json:"cidr"`     // e.g. 10.11.222.0/24
	IPStart string `json:"ipStart"`  // e.g. 10.11.222.10
	IPEnd   string `json:"ipEnd"`    // e.g. 10.11.222.250

	// DNS / DHCP
	AllowDNS   bool     `json:"allowDNS"`
	DNSServers []string `json:"dnsServers"`
	DNSDomain  string   `json:"dnsDomain"`
	AllowDHCP  bool     `json:"allowDHCP"`

	// IPv6
	IPv6 IPv6Mode `json:"ipv6"`

	// Multicast / Broadcast
	EnableBroadcast bool `json:"enableBroadcast"`
	MulticastLimit  int  `json:"multicastLimit"` // 0..1024, typical 32/64/256
	AllowMDNS       bool `json:"allowMDNS"`

	// Routes
	Routes []Route `json:"routes"`

	// Traffic policy
	RulesSource string `json:"rulesSource"` // ZeroTier Rules text
}

// low-level partial update
func (m *NetworkManager) patchNetwork(networkId string, obj map[string]any) error {
	payloadBytes, _ := json.Marshal(obj)
	url := "http://localhost:" + strconv.Itoa(m.apiPort) + "/controller/network/" + networkId + "/"
	req, err := http.NewRequest("POST", url, bytes.NewBuffer(payloadBytes))
	if err != nil {
		return err
	}
	req.Header.Set("X-Zt1-Auth", m.authToken)
	req.Header.Set("Content-Type", "application/json")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return errors.New("controller patch failed, status " + strconv.Itoa(resp.StatusCode))
	}
	return nil
}

func (m *NetworkManager) ApplyAdvancedSettings(netid string, s *AdvancedNetworkSettings) error {
	patch := map[string]any{}

	// IP pools from CIDR/IPStart/IPEnd
	if s.CIDR != "" && s.IPStart != "" && s.IPEnd != "" {
		patch["ipAssignmentPools"] = []map[string]string{
			{"ipRangeStart": s.IPStart, "ipRangeEnd": s.IPEnd},
		}
		// v4 assign via controller
		patch["v4AssignMode"] = map[string]bool{"zt": true}
		// Add a default managed route for the pool (safe, user can overwrite with Routes)
		patch["routes"] = []map[string]string{
			{"target": strings.TrimSpace(s.CIDR)},
		}
	}

	// DNS
	if s.AllowDNS {
		patch["dns"] = map[string]any{
			"domain":  s.DNSDomain,
			"servers": s.DNSServers,
		}
	} else {
		patch["dns"] = map[string]any{} // clear
	}

	// DHCP: letting DHCP pass through ZT typically means allow it in rules + bridge mode
	// We don’t run a DHCP server here; we open the path for L2/UDP 67/68.
	// The RulesSource builder below will include DHCP/mDNS if toggled.

	// IPv6 assign modes
	patch["v6AssignMode"] = map[string]bool{
		"zt":      s.IPv6.ZT,
		"rfc4193": s.IPv6.RFC4193,
		"6plane":  s.IPv6.SixPlane,
	}

	// Multicast / broadcast
	patch["enableBroadcast"] = s.EnableBroadcast
	if s.MulticastLimit > 0 {
		patch["multicastLimit"] = s.MulticastLimit
	}

	// Routes (append/override)
	if len(s.Routes) > 0 {
		rs := make([]map[string]string, 0, len(s.Routes))
		for _, r := range s.Routes {
			ent := map[string]string{"target": r.Target}
			if strings.TrimSpace(r.Via) != "" {
				ent["via"] = r.Via
			}
			rs = append(rs, ent)
		}
		patch["routes"] = rs
	}

	// Rules
	if s.RulesSource != "" || s.AllowDHCP || s.AllowMDNS {
		rules := s.RulesSource
		if rules == "" {
			rules = "/* autogenerated */\n"
		}
		// Ensure ARP, DHCP, mDNS allowed if requested
		if s.AllowDHCP && !strings.Contains(rules, "dhcp") {
			rules += `
accept ipprotocol udp and dport 67;   // DHCP server
accept ipprotocol udp and dport 68;   // DHCP client
`
		}
		if s.AllowMDNS && !strings.Contains(rules, "224.0.0.251") {
			rules += `
accept ethertype ipv4 and daddr 224.0.0.251;   // mDNS v4
accept ethertype ipv6 and daddr ff02::fb;      // mDNS v6
`
		}
		// ARP and basic allow
		if !strings.Contains(rules, "arp") {
			rules = "accept ethertype arp;\n" + rules
		}
		// Make sure default allow exists if user didn’t supply policy
		if !strings.Contains(rules, "drop") && !strings.Contains(strings.ToLower(rules), "reject") {
			rules += "\naccept;\n"
		}
		patch["rulesSource"] = rules
	}

	return m.patchNetwork(netid, patch)
}

// Per-member: set activeBridge for a member (controller or a client)
func (m *NetworkManager) SetMemberBridge(netid, memberid string, enable bool) error {
	body := map[string]any{"activeBridge": enable}
	data, _ := json.Marshal(body)
	url := "http://localhost:" + strconv.Itoa(m.apiPort) + "/controller/network/" + netid + "/member/" + memberid
	req, err := http.NewRequest("POST", url, bytes.NewBuffer(data))
	if err != nil {
		return err
	}
	req.Header.Set("X-Zt1-Auth", m.authToken)
	req.Header.Set("Content-Type", "application/json")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return errors.New("failed to set activeBridge, status " + strconv.Itoa(resp.StatusCode))
	}
	return nil
}
